version: '3.8'

services:
  obfuscating-proxy:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    command: ["obfsproxy", "-l", "0.0.0.0:8080", "-t", "deobfuscating-proxy:8081"]
    ports:
      - "8080:8080"

  deobfuscating-proxy:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    command: ["obfsproxy", "-l", "0.0.0.0:8081", "-t", "mock-server:80"]
    ports:
      - "8081:8081"

  mock-server:
    image: nginx:alpine
    volumes:
      - ./mock-server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
