services:
  proxy-client:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    command: ["obfsproxy", "-l", "0.0.0.0:8080", "-t", "proxy-server:8081", "-k", "test-key", "-r", "50", "-c"]
    ports:
      - "8080:8080"

  proxy-server:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    command: ["obfsproxy", "-l", "0.0.0.0:8081", "-t", "mock-server:80", "-k", "test-key", "-r", "50", "-s"]
    ports:
      - "8081:8081"

  mock-server:
    image: nginx:alpine
    volumes:
      - ./mock-server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
